apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPorts
metadata:
  name: restrict-ports
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    message: "Containers must not expose ports below 1024."