apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sports
spec:
  crd:
    spec:
      names:
        kind: K8sPorts
      validation:
        openAPIV3Schema:
          properties:
            message:
              type: string
              description: "Error message to display when the constraint is violated."
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sports

         violation[{"msg": msg}] {
            container := input.review.object.spec.containers[_]
            port := container.ports[_].containerPort
            port < 1024
            msg := sprintf("Container '%s' must not expose port %d (ports below 1024 are not allowed).", [container.name, port])
        }