apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdenyroot
spec:
  crd:
    spec:
      names:
        kind: K8sDenyRoot
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sroot
        violation[{"msg": "Containers must not run as root"}] {
            input.review.object.spec.containers[_].securityContext.runAsUser == 0
        }
