apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: app
        image: nginx:latest
        securityContext:
          runAsNonRoot: true #this should cause the pipeline to fail when set as false
        ports:
        - containerPort: 8080 #this should cause the pipeline to fail when port is set below 1024
        volumeMounts:
        - mountPath: /data
          name: data-volume
          readOnly: true #this should cause the pipeline to fail when set as false
      volumes:
      - name: data-volume
        emptyDir: {}