apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configs/app-config.yaml
  - configs/secret-provider.yaml
  - configs/db-init-configmap.yaml
  - policies/network-policy.yaml
  - policies/pod-security-policy.yaml
  - rbac/service-account.yaml
  - rbac/psp-rbac.yaml
  - workloads/db.yaml
  - workloads/nodejs.yaml
  - workloads/mailcatcher.yaml

vars:
  - name: SECRET_NAME
    objref:
      kind: SecretProviderClass
      name: bc-db-credentials
      apiVersion: secrets-store.csi.x-k8s.io/v1
  - name: IAM_ROLE_ARN
    objref:
      kind: ServiceAccount
      name: jomacs-capstone-service-account
      apiVersion: v1
  - name: AWS_REGION
    objref:
      kind: ConfigMap
      name: aws-logging
      apiVersion: v1
  - name: CLUSTER_NAME
    objref:
      kind: ConfigMap
      name: aws-logging
      apiVersion: v1
  - name: FLUENT_BIT_ROLE_ARN
    objref:
      kind: ServiceAccount
      name: fluent-bit
      apiVersion: v1 