apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DATABASE_HOST: "db-service"
  DATABASE_SCHEMA: "bc"
  DATABASE_PORT: "5432"
  URL: "http://nodejs-service:80"
  MAIL_HOST: "mailcatcher-service"
  MAIL_PORT: "1025"
  MAIL_SECURE: "false"
  MAIL_USERNAME: "mailcatcher"
  MAIL_PASSWORD: "mailcatcher" 