apiVersion: v1
kind: ServiceAccount
metadata:
  name: jomacs-capstone-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: ${IAM_ROLE_ARN}  # This will be replaced by Kustomize 